#!/bin/bash


echo "🧹 Cleaning up EMPTY files in JSON - probably generated by some wrong gcloud command.."
find db/fixtures/ -size 0 -name \*json | xargs ls -al
find db/fixtures/ -size 0 -name \*json -print0 | xargs -0 rm

